step

diff --git a/.forgejo/workflows/build.yaml b/.forgejo/workflows/build.yaml
--- a/.forgejo/workflows/build.yaml
+++ b/.forgejo/workflows/build.yaml
@@ -25,10 +25,10 @@ on:
 jobs:
   try:
     name: try
-    # runs-on: codeberg-small
-    runs-on: docker
-    container:
-      image: ghcr.io/catthehacker/ubuntu:custom-24.04
+    runs-on: codeberg-small
+    # runs-on: docker
+    # container:
+    #   image: ghcr.io/catthehacker/ubuntu:custom-24.04
     steps:
       - uses: actions/checkout@v4
       - name: Install buildah
@@ -37,11 +37,18 @@ jobs:
           apt-get install buildah -y
       - name: Setup buildah
         uses: https://codeberg.org/qikp/setup-buildah@main
+      - name: Debug
+        run: |
+          grep -E '/docker|/lxc|/kubepods' /proc/1/cgroup || [ -f /.dockerenv ] && echo "inside container"
+          cat /proc/sys/kernel/unprivileged_userns_clone
+          command -v newuidmap newgidmap || echo "missing uidmap package"
+          id -un
+          awk -F: -v u="$(id -un)" '$1==u{print $0}' /etc/subuid /etc/subgid || echo "no subuid/subgid entry for $(id -un)"
       - name: Build and push
         run: |
           mkdir -p target/tmp/
           echo test > target/tmp/cmha_x86_64
-          buildah build -f Containerfile --build-arg target_file=target/tmp/cmha_x86_64 \
+          buildah --log-level=debug build -f Containerfile --build-arg target_file=target/tmp/cmha_x86_64 \
           -t docker.io/library/giggio/cmha:0.1.0-amd64 -t docker.io/library/giggio/cmha:amd64 \
           --platform linux/amd64 --signature-policy ./buildah-policy.json --format=docker --pull .
 #  build:
